### ISSUE TITLE
Client login fails depending on method how server is started.

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2STAGE/B2STAGE-GridFTP#26]
Hello, 
I am using centos7.3, irods 4.2.1 and the latest checkout of the B2STAGE code.

I found something curious.
Usually you can restart a gridFTP server in two ways:
1. `/etc/init.d/globus-gridftp-server restart`
2. `service globus-gridftp-server restart`

However, as soon as I install the B2STAGE and I restart the server with the second option I always receive the following error:

```sh
[admincentos@alice-centos ~]$ globus-url-copy -list gsiftp://alice-centos/aliceZone/home/alice/
gsiftp://alice-centos/aliceZone/home/alice/


error: globus_ftp_client: the server responded with an error
530 530-Login incorrect. : /home/admincentos/B2STAGE-GridFTP/DSI/globus_gridftp_server_iRODS.c:globus_l_gfs_iRODS_make_error:580:
530-iRODS DSI. Error: 'clientLogin' failed.. CAT_INVALID_AUTHENTICATION: , status: -826000.
530-
530 End.
```

When I use option 1 to restart the server everything works normal.

**Comment by vladimir-mencl-eresearch** [comment]
Hi, I'd suspect this is due to the variable settings not making it through.

The way this module links against iRODS-4 libraries, it needs LD_LIBRARY_PATH and LD_PRELOAD set in the environment globus-gridftp-server is starting from.

The setup instructions for this module add these variables to `/etc/init.d/globus-gridftp-server`.

However, on CentOS 7.3, I'd expect that `service globus-gridftp-server restart` launches the GridFTP server via `systemd`, bypassing the file with the variable settings.

I have not recently checked how current GridFTP server installs on CentOS - but I'd expect it now brings in a systemd unit file.  It's just my suspicion - but if that's the case, you'll need to add the variable settings also to the unit file.

Please check if that works - and if so, the documentation of this module will have to be updated accordingly.

Cheers,
Vlad
