### ISSUE TITLE
Compiling against iRODS 4

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/B2STAGE-GridFTP#7]
I'm opening this issue to track the work related to the compilation of the DSI library againsts iRODS 4.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Roberto,

Thanks for bringing this up.

I've just started looking into it.

And I think I got it working.

Here is the list of issues I ran into - with proposed/mostly implemented solutions:
* The obvious one is figuring out what IRODS_PATH should be set to.  
 * The key paths we need are /usr/include/irods and /usr/lib/libRodsAPIs.a
 * So I think the way to go is to set IRODS_PATH to /usr, along the same lines as GLOBUS_LOCATION handles RPM-based Globus installs.
* Then, the next one is handling this as a special case in CMakeList.txt to come up with different list of paths to use in the INCLUDE path and a different path to libRodsAPIs.a
 * I have this implemented based on ````if ($ENV{IRODS_PATH} STREQUAL "/usr")```` - and setting CMake variables  irods_include_path_list and irods_link_obj_path that get used further down in the file instead of directly pointing to the files / directories.

* The next issue is that iRODS is now developed as a C++ source code, with support to be used in a C program.
 * The minimal fix is to include rodsClient.hpp instead of rodsClient.h - and that seems to work (with the single exception just below).

* The signature for the clientLogin function has changed: it requires two additional parameters - which default to NULL in C++ mode, but must be explicitly specified in C mode.
 * I think I would rather avoid flipping our code to C++ - that could pop up a number of other issues.
 * So I would rather ````#ifdef```` this (based on something that determines whether we are compiling against iRODS 4).

* And, iRODS 4 brings in dependency on external libraries - to link against libRodsAPIs.a, you have to throw in also the boost libraries and the jansson JSON parser.  That is still easy to do...

* But, by default, libjansson.a is built without PIC support and cannot be used in a .so library.  I've just found where this can be fixed in the iRODS Makefile and will be submitting a pull request shortly...

If you are fine with the proposed solution, I am happy to package my working directory into a pull request... :-)

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
FYI, regarding the -fPIC flag:
Issue reported against iRODS: https://github.com/irods/irods/pull/2623
Pull request: https://github.com/irods/irods/pull/2623

**Comment by vladimir-mencl-eresearch** [comment]
Hi Roberto,

Going over "git diff", I see I missed one extra tweak: iRODS 4 also needs "-lrt" added to the link flags (to get the routine ````clock_gettime```` used by boost::chrono).  Can be easily fixed the same way other library dependencies get fixed.

Cheers,
Vlad

**Comment by muccix** [comment]
Hi Vlad,

great! I faced the same problems you reported in your issues list. If you have almost finished implementing the modification, I can wait for you pull request.

By the way, I am trying to refactor the CMakeList.txt adding some Find_packages to make easier the deploy: I will wait for your pull request before proceeding on this.

Cheers,
Roberto
